apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-store2
  template:
    metadata:
      labels:
        app: pet-store2
    spec:
      containers:
        - name: pet-store2
          image: pet-store2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
