apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store2
  namespace: pet-business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-store2
  template:
    metadata:
      labels:
        app: pet-store2
    spec:
      containers:
        - name: pet-store2
          image: pet-store1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: STORE_ID
              value: "2"
            - name: MONGO_URI
              value: "mongodb://database:27017"
            - name: NINJA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ninja-api-secret
                  key: NINJA_API_KEY
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
