apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-order
env:
  - name: MONGO_URI
    value: "mongodb://database:27017"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-order
  template:
    metadata:
      labels:
        app: pet-order
    spec:
      containers:
        - name: pet-order
          image: pet-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
