apiVersion: v1
kind: Service
metadata:
  name: pet-order
  namespace: pet-business
spec:
  selector:
    app: pet-order
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
