apiVersion: v1
kind: Service
metadata:
  name: pet-order-service
spec:
  selector:
    app: pet-order
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30081
